### ISSUE TITLE
Inserting images

### ISSUE THREAD

**Issue by Rahbaran** [JackAdams/meteor-editable-text-wysiwyg-bootstrap-3#7]
Either by:
- Drag 'n drop
- per upload button
- inserting the embedded link automatically shows the image

**Comment by JackAdams** [comment]
Set `EditableText.maximumImageSize = 200000;` in a client/server (both) file and you should be able to cut and paste images in.  I can't remember if drag and drop works.  It might.

**Comment by JackAdams** [comment]
Yep, just did a quick test.  You can cut and paste images in or drag and drop but, fair warning, those images are stored in the db field as base-64 encoded text, so the db document gets huge.  Not good for subscribing and re-subscribing frequently.  That's why I suggested setting maximum image size to 200k in the comment above.
